- distro/pom.xml
See OpenMRS Talk thread: https://talk.openmrs.org/t/reporting-module-version-0-10-4-used-in-bahmni-0-89-error-500/12311?u=mksrom
> rbuisson | Upgrade Reporting module to version 1.12.0

- distro/pom.xml
JIRA link : https://bahmni.atlassian.net/browse/BAH-520
Changed all the Snapshots to Release versions and added dependencies accordingly
> BAH-520: Release of all OMODs for 0.91

- distro/pom.xml
https://bahmni.atlassian.net/browse/BAH-1028
> BAH-1028 | Update Bahmni IE Apps dependency to 1.1.0-SNAPSHOT

- distro/pom.xml
https://bahmni.atlassian.net/browse/BAH-1092
> Bindu | BAH-1092 | upping the operation theater omod version to latest released version

- distro/pom.xml
- Upgrades bacteriology version to 1.3.0
> BAH-1649 - | Rohit | - Upgrades bacteriology version to 1.3.0

- distro/pom.xml
Co-authored-by: deepthi-m <deepthi.mantena@thoughtworks.com>
> BAH-1951 | Package open concept lab omod

- package/docker/openmrs/Dockerfile
- package/resources/openmrs-runtime.properties
- Adds liquibase-runtime.properties
- Added zeroDateTimeBehavior attibute in connection url to resolve zero date value exception
> BAH-1992 - | Rohit | - Adds liquibase-runtime.properties file with adding zeroDateTimeBehavior attrib to resolve zero date value exception

- distro/pom.xml
- package/docker/openmrs/Dockerfile
- Adding latest fhir2-1.4.0 omod with OMRS:2.4.2 changes
- Upgrades initializer omod version to 2.3.0-SNAPSHOT
> BAH-1975 - | Bindu, Rohit | - Upgrades latest fhir2-1.4.0 omod

- package/docker/openmrs/bahmni_startup.sh
- Comments running atomfeed migrations as migrations are moved to bahmni-core
https://github.com/Bahmni/bahmni-core/pull/144
- Comments adding jars to classpath code
https://bahmni.atlassian.net/browse/BAH-2086
> BAH - 2086 - Comments running atomfeed migrations as migrations are moved to bahmni-core

- package/helm/openmrs/templates/deployment.yaml
- package/helm/openmrs/templates/volumes/openmrs-initializer-checksums.yaml
- package/helm/openmrs/values.yaml
Co-authored-by: MOHANKUMAR T <mohan13081999@gmail.com>
> BAH-2157 | Added Persistent Volume for openmrs initializer-checksums

- package/helm/openmrs/templates/deployment.yaml
- package/helm/openmrs/templates/volumes/openmrs-clinical-forms.yaml
- package/helm/openmrs/values.yaml
This pr adds the volume mount for persisting forms created from implementer-interface.
> BAH-2163 | Added Persistent Volume for implementer-interface

- distro/pom.xml
- openmrs-module-bahmni.configuration/pom.xml
- package/docker/openmrs/Dockerfile
JIRA card -> [https://bahmni.atlassian.net/browse/BAH-2222](https://bahmni.atlassian.net/browse/BAH-2222)
This PR can be merged only when the below PR raised to bahmni-core is merged
[https://github.com/Bahmni/bahmni-core/pull/151](https://github.com/Bahmni/bahmni-core/pull/151)
> Bindu | BAH-2222 | Upgrade OMRS version to 2.5.5

- package/docker/openmrs/Dockerfile
JIRA - [https://bahmni.atlassian.net/browse/BAH-2274](https://bahmni.atlassian.net/browse/BAH-2274)
> BAH-2274 | Siva Reddy | OpenMRS upgrade to 2.5.7-SNAPSHOT

- .github/workflows/build_publish_openmrs.yml
- Uses versioning utility from bahmni-infra-utils
> BAH-2287 | Implement release versioning

- .github/workflows/build_publish_openmrs.yml
**Description**
This PR is about : 
-  Supporting multi architecture docker image builds.
> BAH-2175 | Support multi architecture docker image builds

- package/docker/openmrs/Dockerfile
- package/docker/openmrs/bahmni_startup.sh
- Remove unused code and download steps from the Dockerfile that has been added as part of this  [code](https://github.com/Bahmni/bahmni-core/pull/144) itself.
> BAH-2389 | Removed unused variables and commands

- distro/pom.xml
JIRA - [https://bahmni.atlassian.net/browse/BAH-2464](https://bahmni.atlassian.net/browse/BAH-2464)
> Siva Reddy | BAH-2464 | Adding Dependency of bahmni-commons

- distro/pom.xml
> BAH-2674 | Deploying teleconsultation module to envs

- .github/workflows/build_publish_openmrs.yml
- .github/workflows/validate_pr.yml
https://bahmni.atlassian.net/jira/software/c/projects/BS/boards/49?selectedIssue=BS-39
> BS-39 | Siva,Vijay | Publish openmrs-distro-bahmni with SNOMED image tags

- package/docker/openmrs/bahmni_startup.sh
JIRA card -> [https://bahmni.atlassian.net/browse/BAH-2650](https://bahmni.atlassian.net/browse/BAH-2650)
> Bindu, Umair | BAH-2650 |Fix patient document thumbnail issue with latest OpenMRS image

- package/docker/openmrs/Dockerfile
- package/docker/openmrs/bahmni_startup.sh
JIRA card -> https://bahmni.atlassian.net/browse/BAH-2650
> Bindu | BAH-2650 | move the command from startup script to dockerfile as this is failing in the env's

- package/docker/openmrs/bahmni_startup.sh
- package/helm/openmrs/templates/configMap.yaml
- package/helm/openmrs/values.yaml
JIRA card -> [https://bahmni.atlassian.net/browse/BAH-2650](https://bahmni.atlassian.net/browse/BAH-2650)
> Bindu, Umair | BAH-2650 | Introduce OMRS_DOCKER_ENV to set the folder permissions

- package/docker/openmrs/Dockerfile
JIRA card -> [https://bahmni.atlassian.net/browse/BAH-2784](https://bahmni.atlassian.net/browse/BAH-2784)
> Bindu | BAH-2784 | update the image to release version and run container as root user

- .dockerignore
- distro/pom.xml
- package/docker/openmrs/Dockerfile
- Upgrading webservices-rest version to 2.39.0-SNAPSHOT
> BAH-2407 - [ Rohit ] - Upgrades webservices-rest version to 2.39.0-SNAPSHOT

- distro/pom.xml
JIRA - https://bahmni.atlassian.net/browse/BS-44
> Siva Reddy | BS-44 | Update FHIR TS Integration Module

- distro/pom.xml
- openmrs-module-bahmni.configuration/pom.xml
- package/docker/openmrs/Dockerfile
- Upgrades openmrs version to 2.5.10 in dependencies
> BAH-2407 - [ Rohit ] - Upgrades openmrs version to 2.5.10

- .github/workflows/build_publish_openmrs.yml
JIRA - https://bahmni.atlassian.net/browse/BS-42
> Siva Reddy | BS-42 | deployment to SNOMED Environment

- distro/pom.xml
This PR still needs update raising this as a placeholder for further changes
> BAH-2849-update | Updated the versions to the latest

- distro/pom.xml
- package/docker/openmrs/Dockerfile
JIRA - https://bahmni.atlassian.net/browse/BS-99
- Upgrading Iniz module version to 2.5.0-SNAPSHOT (support for drugs mappings)
- Upgrading OpenMRS version latest 2.5.x (support not available in 2.5.10 version)
> Siva Reddy | BS-99 | Adding SNOMED Codes to Drugs #103

- distro/pom.xml
- package/docker/openmrs/Dockerfile
JIRA - https://bahmni.atlassian.net/browse/BS-102
> Siva Reddy | BS-102 | Adding dependency of CDSS Module

- README.md
JIRA - https://bahmni.atlassian.net/browse/BS-113
> BS-113 | Update ReadMe

- package/docker/openmrs/Dockerfile
[Ritesh] Copy updated_tomcat_context.xml in container for bahmni-events
> [Ritesh] Copy updated_tomcat_context.xml in container for bahmni-events

- package/docker/openmrs/Dockerfile
- package/docker/openmrs/bahmni_startup.sh
- package/docker/openmrs/templates/rulesengine-concept.properties.template
Asana link - https://app.asana.com/0/1204322126657135/1204551237996191/f
Jira Link - https://bahmni.atlassian.net/browse/BAH-3077
**Summary:** For the rule drop down to be visible we need to add this property file as configuration
> Include property files for rules to be visible

- package/docker/openmrs/templates/rulesengine-concept.properties.template
Asana link - https://app.asana.com/0/1204322126657135/1204551237996191/f
Jira Link - https://bahmni.atlassian.net/browse/BAH-3056
> Soorya | BAH-3056 | Fix the env variables naming

- package/docker/openmrs/Dockerfile
- package/docker/openmrs/bahmni_startup.sh
- package/docker/openmrs/templates/appointment.properties.template
- Added properties file to fetch in appointments module
> BAH-2181 | Added properties file to fetch in appointments module

- distro/pom.xml
JIRA - https://bahmni.atlassian.net/browse/BS-167
> BS-167 | Changes for FHIR Exports

- distro/pom.xml
- package/docker/openmrs/Dockerfile
JIRA https://bahmni.atlassian.net/browse/BAH-3110
- Upgrading OpenMRS version to 2.5.12
- bahmnicore 1.2.0-SNAPSHOT (includes SNOMED milestone 1 changes)
> BAH-3110 | Upgrade OpenMRS version to 2.5.12

- distro/pom.xml
- package/docker/openmrs/Dockerfile
JIRA Ref [BAH-3081](https://bahmni.atlassian.net/browse/BAH-3081)
> BAH-3081 | upgrade OCL version from 1.3.0 to 2.1.0

- package/docker/openmrs/Dockerfile
- package/resources/purge_files.sh
Jira: https://bahmni.atlassian.net/browse/BS-204
* Added a cron job to purge the frhir export files which are older that 48 hours
> BS-204 | Cron job to Purge Old Jobs (> 48 hours)

- distro/pom.xml
JIRA https://bahmni.atlassian.net/browse/BS-206
> BS-206 | Updating FHIR2Extension module

- package/resources/fhir-export-anonymise-config.json
- Changing method name for BirthDate and DeceasedDateTime to `firstOfMonth`
> Changing method name for BirthDate and DeceasedDateTime to firstOfMonth

- package/docker/openmrs/Dockerfile
- package/resources/fhir-export-anonymise-fixed-config.json
- package/resources/fhir-export-anonymise-random-config.json
created fhir anonymise config for fixed and random and updated docker file
https://bahmni.atlassian.net/browse/BS-191
https://bahmni.atlassian.net/browse/BS-192
> BS 191 | BS 192 | Bulk FHIR export of Anonymised Patient Data from Bahmni (Randomize with Randome and Fixed Value)

- package/docker/openmrs/Dockerfile
- package/resources/fhir-export-anonymise-correlate-config.json
- package/resources/fhir-export-anonymise-fixed-config.json
- package/resources/fhir-export-anonymise-random-config.json
Anonymise using Correlation 
https://bahmni.atlassian.net/browse/BS-189
PATIENT
```
{
"resourceType": "Patient",
"id": "f73cefd2dfa583d9091dfdda93830429c6e8f7ee2f34f4e5df6283b8a3a1e5c4",
"meta": {
"lastUpdated": "2023-08-11T09:39:10.000+00:00"
},
"identifier": [
{
"id": "49d94f91-9cda-4ded-baa7-901d291eea1c",
"use": "official",
"type": {
"coding": [
{
"code": "81433852-3f10-11e4-adec-0800271c1b75"
}
],
"text": "Patient Identifier"
},
"value": "GAN203012"
}
],
"active": true,
"gender": "male",
"birthDate": "2018-01-01",
"deceasedBoolean": false
}
```
CONDITIONS
```
{
"resourceType": "Condition",
"id": "c5a2c976-f4f4-472f-8e2e-703a15cfb9a3",
---
---
"subject": {
"reference": "Patient/f73cefd2dfa583d9091dfdda93830429c6e8f7ee2f34f4e5df6283b8a3a1e5c4"
},
"onsetDateTime": …
```
> BS-189 | Siva,Vijay | add correlate feature

- distro/pom.xml
- package/docker/openmrs/Dockerfile
Asana Link: https://app.asana.com/0/1204322126657135/1205069439065522/f
> Updated openmrs, FHIR version for lablite module

- distro/pom.xml
JIRA -> [BAH-3226](https://bahmni.atlassian.net/browse/BAH-3226)
In this PR, the Bed Management module version within the openmrs-distro-bahmni project is 5.13.0, which is upgraded to version 5.14.0-SNAPSHOT.
> [Parvathy, Rahul] | BAH-3168 | Add. Bump Bed Management Version

- distro/pom.xml
Asana:https://app.asana.com/0/1204322126657135/1205582341920482/f
> update. fhir,fhir2Extension-omod versions

- distro/pom.xml
- package/docker/openmrs/Dockerfile
- package/docker/openmrs/templates/appointment.properties.template
Added bahmni-events module and refactored properties file.
> BAH-2962 | Added bahmni-events module and refactored properties file.

- distro/pom.xml
Upgraded communications module version to 1.2.0-SNAPSHOT .
> BAH-2962 | Upgraded communications module version to 1.2.0-SNAPSHOT .

- README.md
- distro/pom.xml
- package/docker/openmrs/Dockerfile
- package/resources/fhir-export-anonymise-config.json
JIRA : https://bahmni.atlassian.net/browse/BS-262
- Adding FHIR Terminology Services and CDSS OMODs
- Adding config for exporting patient data in FHIR format
> BS-262 | Bundling CDSS and Terminology Service OMODs

- distro/pom.xml
Asana Link -> [https://app.asana.com/0/1204322126657135/1205830700602326/f](https://app.asana.com/0/1204322126657135/1205830700602326/f)
> Bindu | Add reportingCompatibility to enable CohortBuilder feature in openmrs

- distro/pom.xml
Asana - https://app.asana.com/0/1204322126657135/1206085816519258
Add ipd omod dependency to pom file
> A-1206085816519258 | Automate IPD omod deployment to QA and UAT environments

- distro/pom.xml
BAH-3349 || Updated the webServicesRestVersion
> BAH-3349 || Updated the webServicesRestVersion

- distro/pom.xml
- package/docker/openmrs/Dockerfile
Remove Fhir2 dependencies as it will be added through docker resources
- https://github.com/cureinternational/cure-bahmni-docker/pull/90
> Arjun | Fhir2 omod skip for Distro

- distro/pom.xml
- package/docker/openmrs/Dockerfile
JIRA -> [BAH-3811](https://bahmni.atlassian.net/browse/BAH-3811)
In this PR, the reportingcompatibility-omod v2.0.9ht into bahmni/openmrs image.
**Features Introduced:**
- **Cohort Builder**: Allows creation and management of static or dynamic lists of patients, such as 'all male patients over age 65'.
- **Data Exports**: Transforms patient data into a CSV file, providing a one-row-per-patient output for reporting and analysis.
- **Row-per-obs Data Exports**: Exports a new row for each observation for patients with multiple observations stored for a selected concept.
- **Schema Reports**: Provides XML-based reports.
- **Cohort Reports**: Defines reports that contain indicators representing the number of patients in a particular cohort.
> BAH-3811 | Add. reportingcompatibility-omod 2.0.9

- distro/pom.xml
- package/docker/openmrs/Dockerfile
JIRA -> [BAH-3839](https://bahmni.atlassian.net/browse/BAH-3839)
In this PR, the medication-administration-omod v1.0.0-SNAPSHOT is introduced into bahmni/openmrs image.
**Features Introduced:**
- **Medication administration Feature**: Allows creation and administration of medication.
> BAH-3839 | Add. medication-administration-omod v1.0.0-SNAPSHOT

- package/helm/openmrs/templates/hpa.yaml
This PR upgrades the HPA configuration to the stable API version.
JIRA: https://bahmni.atlassian.net/browse/BAH-3911
> BAH-3911 | Upgrade HPA to stable API

- distro/pom.xml
This PR updates the OpenMRS community maintained modules to the latest released version.
1. https://github.com/openmrs/openmrs-module-addresshierarchy/compare/2.14.2...2.17.0
2. https://github.com/openmrs/openmrs-module-appframework/compare/2.16.0...2.17.0
3. https://github.com/openmrs/openmrs-module-emrapi/compare/1.35.0...1.36.0
4. https://github.com/openmrs/openmrs-module-owa/compare/1.13.0...1.14.0
5. https://github.com/openmrs/openmrs-module-htmlwidgets/compare/1.10.0...1.11.0
6. https://github.com/openmrs/openmrs-module-idgen/compare/4.7.0...4.10.0
7. https://github.com/openmrs/openmrs-module-legacyui/compare/1.13.0...1.16.0
8. https://github.com/openmrs/openmrs-module-metadatamapping/compare/1.5.0...1.6.0
9. https://github.com/openmrs/openmrs-module-metadatasharing/compare/1.8.0...1 …
> BAH-4022 | Upgrade OpenMRS community modules to latest version

- distro/pom.xml
This PR upgrades the modules to released versions of the dependencies
> BAH-3806 | Upgrade modules to released versions

- distro/pom.xml
This PR upgrades the version of appointments and ipd module to include the fix for ipd-events-config-file-path property not being picked up.
JIRA: https://bahmni.atlassian.net/browse/BAH-4096, https://bahmni.atlassian.net/browse/BAH-4093
> BAH-3806 | Upgrade versions of Appointments and IPD Module

- distro/pom.xml
- openmrs-module-bahmni.configuration/pom.xml
- pom.xml
JIRA -> [BAH-4097](https://bahmni.atlassian.net/browse/BAH-4097)
For Standard Release.
> BAH-4097 | Add. Bump Version 0.94 -> 1.1

- distro/pom.xml
- pom.xml
Convo: https://bahmni.slack.com/archives/C03LWT96L/p1738940074762079
> Fixed Bahmni Maven Repositories.

- distro/pom.xml
JIRA. -> [FM2-658](https://openmrs.atlassian.net/browse/FM2-658)
2.3.0-SNAPSHOT -> 2.4.0-SNAPSHOT
This PR enhances the OpenMRS FHIR Condition resource by adding support for consultation notes. The note field, which aligns with the HL7 FHIR R4 specification, is now mapped from the additional_detail field in the OpenMRS Condition model. This ensures that clinicians can access important contextual information when reviewing a patient's condition.
Key Changes
- Updated ConditionTranslatorImpl.java to map additional_detail to the note field.
- Added unit tests in ConditionTranslatorImplTest.java to validate the inclusion of notes.
> FM2-658 | Add. Bump fhir2 Module

- distro/pom.xml
This PR upgrades the modules that has issues with OpenMRS startup failure due to dependency on concrete implementation classes.
> Fix. OpenMRS startup failure due to dependency on concrete implementation classes
