- package/docker/openmrs/Dockerfile
The following fixes has been made.
- Fixed a missed directory name in Dockerfile
- Updated base image version to 2.1.6-SNAPSHOT as log4j fix has been done in OpenMRS Platform 2.1.6
> Fix. OpenMRS Container startup failure

- distro/pom.xml
The build started taking longer time because of some obsolete repositories which are not responding
> BAH-1781 | Fix. Build taking longer time

- package/docker/openmrs/Dockerfile
- package/docker/openmrs/bahmni_startup.sh
When restarting OpenMRS container the soft link creation step fails and that step can be done only once in the build step. Hence moving the steps to Dockerfile from startup script.
> BAH-1303 | fix. move soft link creation to Dockerfile

- distro/pom.xml
This PR updates Operation Thaeter module version to 1.6.0 to incorporate the fix for [OTM-3](https://issues.openmrs.org/browse/OTM-3) issue.
> OTM-3 | Updates operation theater version

- .github/workflows/build_publish_openmrs.yml
- distro/pom.xml
- openmrs-module-bahmni.configuration/pom.xml
This PR is about - 
- Upgrades openmrs version to 2.4.2 and upgrades module versions compatible to openmrs:2.4.2
- Changes branch name as OMRS-master-2.4 in github workflow
> Bah 1649 - Upgrades openmrs version to 2.4.2 and upgrades module versions compatible to openmrs:2.4.2

- package/docker/openmrs/Dockerfile
- package/docker/openmrs/bahmni_startup.sh
This PR adds a MySQL command that clears the value of `searchIndex.Version` Global property on every restart, which would eventually trigger a search index rebuild. 
Other approach: 
There is also [REST endpoint](https://rest.openmrs.org/?javascript#update-search-index) exposed by OpenMRS to trigger a rebuild, but it is difficult to trigger it on every restart and this would also need authentication. 
Reference: 
1. JIRA : https://bahmni.atlassian.net/browse/BAH-1679
2. https://talk.openmrs.org/t/rebuild-search-index-from-mysql-or-maven/4446/11
3. https://github.com/openmrs/openmrs-core/blob/2.3.0/api/src/main/java/org/openmrs/util/OpenmrsConstants.java#L597
> BAH-1679 | Add SQL command to trigger search index rebuild

- package/docker/openmrs/Dockerfile
- package/docker/openmrs/bahmni_startup.sh
This is a story. https://bahmni.atlassian.net/browse/BAH-1932
Liquibase migrations are not running due to excluded dependency of "logback-classic" from liquibase-core in openmrs-core
Add missing dependencies that have been generated due to version upgrade.
Update command to add missing libraries to classpath
- udpated
Dockerfile
bahmni_startup.sh
The screenshots for successful docker run has been added on the ticket
> BAH-1932 [Docker] Liquibase migrations are not running due to excluded dependency of "logback-classic" from liquibase-core in openmrs-core

- distro/pom.xml
- package/docker/openmrs/Dockerfile
JIRA card -> [https://bahmni.atlassian.net/browse/BAH-2028](https://bahmni.atlassian.net/browse/BAH-2028)
As part of this PR we are,
- Upgrading fhir2 module from 1.4.0 to 1.5.0
- Removing fhir2 custom module from the resource folder.
> Bindu | BAH-2028 | commons-io mvn dependency from fhir2 module conflicts with openmrs-core

- distro/pom.xml
- Upgrading metadata mapping version to 1.5.0 to resolve fetching identifier-sources issues
- Below is the card for this issue: https://bahmni.atlassian.net/browse/BAH-1814
> BAH-1814 - | Rohit | - Upgrades metadata mapping version to 1.5.0 to resolve fetching identifier-sources issues

- distro/pom.xml
- Upgrading legacy ui version to 1.13.0
> BAH-2590 - Upgrades legacyui version to 1.13.0 to resolve csrf issue

- .github/workflows/build_publish_openmrs.yml
- .github/workflows/validate_pr.yml
In this PR, caching the maven dependencies which improves the build time based on hash of pom files. If the content of pom.xml changes, GHA build creates hash again.
1st Run: 
2nd Run:
> Siva Reddy | Caching maven dependencies

- distro/pom.xml
This PR updates bahmni core version and fhir2extension module versions to the next snapshots which would allow testing BAH-1664 & BAH-2165
> BAH-2849 | Update versions of Bahmni-core and FHIR2Extension Modules

- package/docker/openmrs/Dockerfile
- package/docker/openmrs/bahmni_startup.sh
- package/docker/openmrs/templates/bahmnicore.properties.template
Reports uploaded from labentry module cannot be accessed due to lack of permission so this PR addresses that issue.
We have created a new folder uploaded_results to upload the reports from labentry module and access them in patient dashboard.
> BAH-1664 | Updated to retrieve files from uploadedresults path uploaded from labentry module.

- package/docker/openmrs/Dockerfile
- package/helm/openmrs/templates/configMap.yaml
- package/helm/openmrs/values.yaml
- package/resources/add_hibernate_properties.sh
- This adds a script to append `c3p0.max_size` property to the openmrs-runtime.properties file.
- Also added the config value to helm charts
> BAH-3060 | Environment variable to override c3p0 max size

- distro/pom.xml
Upgrades OCL omod version from 1.3.0 to 2.1.0 (latest)
Jira Ref: [BAH-3081](https://bahmni.atlassian.net/browse/BAH-3081)
> Kavitha | BAH-3081 | upgrade OCL version from 1.3.0 to 2.1.0

- distro/pom.xml
JIRA -> [BAH-3168](https://bahmni.atlassian.net/browse/BAH-3168)
OpenMRS Team want to package Appointments module with O3. They can’t do that unless the license of this module is compatible with O3. Bahmni Coalition/Community have agreed to make the change to make this module’s license compatible with Bahmni & OMRS licenses. Henceforth the [openmrs-module-appointments](https://github.com/Bahmni/openmrs-module-appointments) and [openmrs-module-teleconsultation](https://github.com/Bahmni/openmrs-module-teleconsultation) gets it's module license changed from AGPLv3 to OpenMRS MPLv2. 
To ensure that the Bahmni LITE/Helm umbrella charts are pulling the new 2.0-snapshot builds of appointment and teleconsultation module, their versions have now been updated to `2.0.0-SNAPSHOT` in this PR.
> [Parvathy, Rahul] | BAH-3168 | Add. Version Update

- distro/pom.xml
JIRA -> [BAH-3228](https://bahmni.atlassian.net/browse/BAH-3228)
In this PR, upgrades Bahmni Commons from its current release version, 1.0.0, to the snapshot version, 1.1.0-SNAPSHOT.
> BAH-3228 | Add. Bump Bahmni Commons Version

- package/docker/openmrs/bahmni_startup.sh
This is a patch fix for https://bahmni.atlassian.net/browse/BAH-2650 which applies folder permissions recursively for document_images and uploaded_results directory.
> BAH-2650 | Fix. Recursively apply folder permission for file uploads

- distro/pom.xml
The following modules to be upgraded in Bahmni OpenMRS distribution to pull in changes as mentioned for individual modules.
[webservices-rest](https://github.com/openmrs/openmrs-module-webservices.rest)
For this module, the version is bumped from 2.39 → 2.41 to pull in a security fix for disabling stack trace in API responses. Commit ref: https://github.com/openmrs/openmrs-module-webservices.rest/commit/7ee4c563d4245546f2ecfa05cac0aa7eb63230c4
(Tested at Bahmni HWC distribution for GoK implementation)
[reporting module](https://github.com/openmrs/openmrs-module-reporting)
For this module, the version is bumped from 1.23.0 → 1.26.0 to fix issue with liquibase StringUtils class def not found error. Commit Ref: https://github.com/openmrs/openmrs-module-reporting/commit/b30da8311beb14d2779cfae …
> BAH-3421 | Update versions for webservices-rest and reporting module

- package/docker/openmrs/Dockerfile
JIRA -> [BAH-3525](https://bahmni.atlassian.net/browse/BAH-3525)
This PR addresses the "Zero date value prohibited" error configuring OMRS_DB_EXTRA_ARGS to include `&zeroDateTimeBehavior=convertToNull.
During openmrs runtime, OMRS_DB_EXTRA_ARGS sets zeroDateTimeBehavior=convertToNull in JdbcUrl. Upon boot up, openmrs utilizes its own startup script to define the jdbc url. OMRS_DB_EXTRA_ARGS appends any provided parameters to the end of the url.
By default, the connector throws an exception when encountering zero date values, as it aligns with JDBC and SQL standards. This behavior can be adjusted using the zeroDateTimeBehavior configuration property.
> BAH-3525 | Add. Configuration Property To Handle Zero date prohibited Error

- distro/pom.xml
JIRA -> [BAH-3808](https://bahmni.atlassian.net/browse/BAH-3808)
In this PR, the ie.apps dependency has been bumped up from 1.3.0 -> 1.4.0-SNAPSHOT. With this upgrade the following changes would be brought into bahmni/openmrs image.
- [BAH-3772](https://bahmni.atlassian.net/browse/BAH-3772) | Persist translations for the imported form if the reference form is not present in the environment
- [BAH-1494](https://bahmni.atlassian.net/browse/BAH-1494) | Feature to download Bahmni form builder forms as a PDF
> BAH-3808 | Add. Bump ie.apps Version

- distro/pom.xml
JIRA -> [BAH-3810](https://bahmni.atlassian.net/browse/BAH-3810)
In this PR, the operationtheater dependency has been bumped up from 1.7.0 -> 1.8.0-SNAPSHOT. With this upgrade the following changes would be brought into bahmni/openmrs image.
- [BAH-3092](https://bahmni.atlassian.net/browse/BAH-3092 ) | Add. Primary Diagnoses in the Surgical Appointment Resource
> BAH-3810 | Add. Bump Operation Theater Version

- distro/pom.xml
JIRA -> [BAH-3809](https://bahmni.atlassian.net/browse/BAH-3809)
In this PR, the operationtheater dependency has been bumped up from 1.8.0-SNAPSHOT -> 1.8.0. With this upgrade the following changes would be brought into bahmni/openmrs image.
- [BAH-3092](https://bahmni.atlassian.net/browse/BAH-3092 ) | Add. Primary Diagnoses in the Surgical Appointment Resource
> BAH-3809 | Add. Bump Operation Theater Version 1.8.0

- package/docker/openmrs/Dockerfile
- package/docker/openmrs/bahmni_startup.sh
- package/docker/openmrs/templates/rulesengine-concept.properties.template
Need to bring the dropdown values for rules like mg/kg, mg/m2, customRule. For these dropdown values to be visible. We need to add concept height and weight in rulesengine-concept.properties file present in openmrs data directory.
Jira Link: https://bahmni.atlassian.net/browse/BAH-3077
> BAH-3077|Added concepts for rulesengine dropdown

- distro/pom.xml
This PR updates the FHIR2 module from 1.10.0-SNAPSHOT version to 2.1.0 version. This is needed for the bundling of IPD features into Bahmni Standard distro. Specifically, this brings in the enhancement for FHIR task resource. 
PR raised by Bahmni IPD Team: https://github.com/openmrs/openmrs-module-fhir2/pull/539
> BAH-3853 | Upgrade FHIR2 module from 1.10.0-SNAPSHOT to 2.1.0

- distro/pom.xml
- package/docker/openmrs/Dockerfile
JIRA -> [BAH-3898](https://bahmni.atlassian.net/browse/BAH-3898)
This pull request introduces new features and configurations to enhance Bahmni's functionality and user experience. Key updates include:
**i) `bahmni-ipd.allowSlotStopOnDrugOrderStop`:**
- **Purpose:** Decides if tasks associated with a drug order should be stopped when the order is stopped from the Patient Dashboard or IPD Dashboard.
- **Default Value:** `true`
**ii) `bahmni.quickLogoutComboKey`:**
- **Purpose:** Allows modification of the secondary key for quick user logout via shortcut keys.
- **Default Value:** `Escape` (Cmd+Esc for Mac, Ctrl+Esc for Windows)
- Detailed configurations can be found in the provided IPD configuration documentation.
**i) Mark Slots as Missed Scheduler:**
- **Job Name:** Mark Appointment As …
> BAH-3898 | Add. Bahmni IPD Omod Version 1.0.0-SNAPSHOT

- package/docker/openmrs/Dockerfile
This PR upgrades the MySQL client binary to the upgraded MySQL 8.0 version
> BAH-3979 | Add. Steps to install upgraded MySQL 8.0 client

- distro/pom.xml
This PR upgrades bedmanagement module version from 5.14.0-SNAPSHOT to 6.0.0-SNAPSHOT.
PR has been merged on bahmniapps repo to make it compatible. https://github.com/Bahmni/openmrs-module-bahmniapps/pull/976
JIRA: https://bahmni.atlassian.net/browse/BAH-4003
> BAH-4003 | Upgrade bedmanagement module version

- distro/pom.xml
This PR rolls-back the appointments module version to 2.0.0 as with 2.0.1 the IPD module fails to load and eventually OpenMRS does not boot up
> BAH-3806 | Revert. Appointments module version to 2.0.0

- distro/pom.xml
This PR intends to avoid appending the assembly Id (distro) to the final distro zip package.
i.e  `distro-1.2.0-SNAPSHOT-distro.zip` ➔ `distro-1.2.0-SNAPSHOT.zip`
> Remove auto-appended assembly-id suffix to final distro zip artefact

- distro/pom.xml
This is a follow-on PR based on the changes discussed [here](https://bahmni.slack.com/archives/C03LWT96L/p1732540018086699).
This PR will ensure the following upgrades:
* Bahmni Core 1.3.0-SNAPSHOT allows Bahmni Core liquibase runnable on Maria DB [reference](https://github.com/Bahmni/bahmni-core/pull/280).
* FHIR2 2.3.0-SNAPSHOT fixes the issue with its api failing to access another modules api [reference](https://openmrs.atlassian.net/browse/FM2-651).
> BAH-4149: Bump Bahmni Core version to 1.3.0-SNAPSHOT and FHIR2 version to 2.3.0-SNAPSHOT.

- distro/pom.xml
JIRA -> [BAH-4160](https://bahmni.atlassian.net/browse/BAH-4160)
This PR upgrades the Legacy UI module in Bahmni from version 1.16.0 to the latest version 1.21.0. The Legacy UI module  upgrade is to leverage new features, improvements, and bug fixes introduced between versions 1.17.0 and 1.21.0.
Between v1.16 and v1.21 of openmrs-module-legacyui, mostly HTML/XML sanitization has been added across multiple areas to enhance security and prevent XSS vulnerabilities. Key updates include privileged-based access to global properties, ensuring that only authorized users can retrieve them. HTML escaping was implemented in various sections, such as autocomplete, datatables, and search suggestions, to ensure proper handling of user-provided data and prevent code injection. Additional fixes …
> [Rahul] | BAH-4160 | Add. Bump Legacy UI Version to 1.21.0

- distro/pom.xml
JIRA -> [BAH-4161](https://bahmni.atlassian.net/browse/BAH-4161)
4.10.0 -> 4.14.0
This PR upgrades the ID Gen module in Bahmni from version 4.10.0 to the latest version 4.14.0. The ID Gen module upgrade is to leverage new features, improvements, and bug fixes introduced between versions 4.10.0 and 4.14.0.
Between v4.10 and v4.14 of openmrs-module-idgen, mostly HTML/XML sanitization has been added to input fields, particularly in the management of Patient Identifier Sources, to enhance security and protect against potential XSS attacks. Authentication is now required for all API calls to strengthen access control. Additionally, UUIDs were generated for all rows in the idgen_auto_generation_option table for MariaDB to ensure data consistency. A fix was also applied to specify …
> BAH-4162 | Add. Bump ID Gen Module Version

- distro/pom.xml
- package/docker/openmrs/Dockerfile
JIRA -> [BAH-4153](https://bahmni.atlassian.net/browse/BAH-4153)
2.5.12 -> 2.5.14
This PR upgrades the `openmrs-core` base image in Bahmni from version `v2.5.12` to the latest version `v2.5.14`. The `openmrs-core` base image upgrade is to leverage new improvements, and bug fixes introduced between versions `v2.5.12` and `v2.5.14`.
Between `v2.5.12` and `v2.5.14` of the `openmrs-core` base image, mostly stricter privilege checks have been added to enhance security. Missing privilege checks were implemented in services like `ConceptService`, `FormService`, and `DatabaseUpdater`, while `AlertService` now requires proper authorization. Enhancements include protecting admin credentials with runtime properties, ensuring secure handling of sensitive data, and setting the appropriate MIME type …
> BAH-4153 | Add. Bump openmrs-core Image Version

- distro/pom.xml
- pom.xml
This PR updates the SNAPSHOT repository URL of nexus-sonatype to point to the Sonatype Central Portal URL. Also, the duplicate repository configurations are removed from the distro module of the project.
> BAH-4187 | Refactor. Maven Repository Configurations

- distro/pom.xml
This PR upgrades the version of address hierarchy module from 2.19.0 to 2.21.0 to resolve issues on the Address Hierarchy Management page from OpenMRS admin page.
Changelog between 2.19.0 and 2.21.0 --> https://github.com/openmrs/openmrs-module-addresshierarchy/compare/2.19.0...2.21.0
JIRA --> https://bahmni.atlassian.net/browse/BAH-4190
> BAH-4190 | Fix. Upgrade address hierarchy module version to 2.21.0

- distro/pom.xml
This PR upgrades the FHIR2 module from 2.4.0-SNAPSHOT to 2.5.0. This is needed to incorporate the Security fixes by OpenMRS team on the module. The @Authrorized annotations are now respected.
Changelog of 2.4.0 to 2.5.0 : https://github.com/openmrs/openmrs-module-fhir2/releases/tag/2.5.0
JIRA: https://bahmni.atlassian.net/browse/BAH-4195
> BAH-4195 | Add. Upgrade FHIR2 module to 2.5.0

- distro/pom.xml
- package/docker/openmrs/Dockerfile
This PR updates the legacy ui module version to 1.22.0. This is needed to resolve the issue with address hierarchy mapping issue. Also OpenMRS core docker version is updated to 2.5.x-nightly to include changes that fixes file upload issues across Admin modules
> BAH-4191 | Upgrade openmrs core version and legacy ui module version

- distro/pom.xml
This PR upgrades the CDSS module version to 1.1.0-SNAPSHOT to incorporate the fix for https://bahmni.atlassian.net/browse/BAH-4202
> BAH-4202 | Upgrade CDSS Module version to 1.1.0-SNAPSHOT
